export const movieData = {
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: "/tncbMvfV0V07UZozXdBEq4Wu9HH.jpg",
      genre_ids: [28, 80, 53, 35],
      id: 573435,
      original_language: "en",
      original_title: "Bad Boys: Ride or Die",
      overview:
        "After their late former Captain is framed, Lowrey and Burnett try to clear his name, only to end up on the run themselves.",
      popularity: 8530.679,
      poster_path: "/nP6RliHjxsz4irTKsxe8FRhKZYl.jpg",
      release_date: "2024-06-05",
      title: "Bad Boys: Ride or Die",
      video: false,
      vote_average: 7.549,
      vote_count: 944,
    },
    {
      adult: false,
      backdrop_path: "/xg27NrXi7VXCGUr7MG75UqLl6Vg.jpg",
      genre_ids: [16, 10751, 12, 35],
      id: 1022789,
      original_language: "en",
      original_title: "Inside Out 2",
      overview:
        "Teenager Riley's mind headquarters is undergoing a sudden demolition to make room for something entirely unexpected: new Emotions! Joy, Sadness, Anger, Fear and Disgust, who’ve long been running a successful operation by all accounts, aren’t sure how to feel when Anxiety shows up. And it looks like she’s not alone.",
      popularity: 4433.962,
      poster_path: "/vpnVM9B6NMmQpWeZvzLvDESb2QY.jpg",
      release_date: "2024-06-11",
      title: "Inside Out 2",
      video: false,
      vote_average: 7.633,
      vote_count: 2087,
    },
    {
      adult: false,
      backdrop_path: "/fDmci71SMkfZM8RnCuXJVDPaSdE.jpg",
      genre_ids: [16, 10751, 35, 28],
      id: 519182,
      original_language: "en",
      original_title: "Despicable Me 4",
      overview:
        "Gru and Lucy and their girls — Margo, Edith and Agnes — welcome a new member to the Gru family, Gru Jr., who is intent on tormenting his dad. Meanwhile, Gru faces a new nemesis in Maxime Le Mal and his femme fatale girlfriend Valentina, forcing the family to go on the run.",
      popularity: 3342.806,
      poster_path: "/wWba3TaojhK7NdycRhoQpsG0FaH.jpg",
      release_date: "2024-06-20",
      title: "Despicable Me 4",
      video: false,
      vote_average: 7.221,
      vote_count: 418,
    },
    {
      adult: false,
      backdrop_path: "/dvBCdCohwWbsP5qAaglOXagDMtk.jpg",
      genre_ids: [878, 28, 35],
      id: 533535,
      original_language: "en",
      original_title: "Deadpool & Wolverine",
      overview:
        "A listless Wade Wilson toils away in civilian life with his days as the morally flexible mercenary, Deadpool, behind him. But when his homeworld faces an existential threat, Wade must reluctantly suit-up again with an even more reluctant Wolverine.",
      popularity: 4270.83,
      poster_path: "/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg",
      release_date: "2024-07-24",
      title: "Deadpool & Wolverine",
      video: false,
      vote_average: 8.2,
      vote_count: 391,
    },
    {
      adult: false,
      backdrop_path: "/dsGwCEO8tda4FlgHKvL95f0oQbH.jpg",
      genre_ids: [16, 878, 28],
      id: 1209290,
      original_language: "en",
      original_title: "Justice League: Crisis on Infinite Earths Part Three",
      overview:
        "Now fully revealed as the ultimate threat to existence, the Anti-Monitor wages an unrelenting attack on the surviving Earths that struggle for survival in a pocket universe. One by one, these worlds and all their inhabitants are vaporized! On the planets that remain, even time itself is shattered, and heroes from the past join the Justice League and their rag-tag allies against the epitome of evil. But as they make their last stand, will the sacrifice of the superheroes be enough to save us all?",
      popularity: 1865.202,
      poster_path: "/a3q8NkM8uTh9E23VsbUOdDSbBeN.jpg",
      release_date: "2024-07-16",
      title: "Justice League: Crisis on Infinite Earths Part Three",
      video: false,
      vote_average: 7.7,
      vote_count: 90,
    },
    {
      adult: false,
      backdrop_path: "/Akv9GlCCMrzcDkVz4ad8MdLl9DK.jpg",
      genre_ids: [16, 35, 10751, 12],
      id: 748783,
      original_language: "en",
      original_title: "The Garfield Movie",
      overview:
        "Garfield, the world-famous, Monday-hating, lasagna-loving indoor cat, is about to have a wild outdoor adventure! After an unexpected reunion with his long-lost father – scruffy street cat Vic – Garfield and his canine friend Odie are forced from their perfectly pampered life into joining Vic in a hilarious, high-stakes heist.",
      popularity: 1701.294,
      poster_path: "/p6AbOJvMQhBmffd0PIv0u8ghWeY.jpg",
      release_date: "2024-04-30",
      title: "The Garfield Movie",
      video: false,
      vote_average: 7.235,
      vote_count: 570,
    },
    {
      adult: false,
      backdrop_path: "/wNAhuOZ3Zf84jCIlrcI6JhgmY5q.jpg",
      genre_ids: [28, 12, 878],
      id: 786892,
      original_language: "en",
      original_title: "Furiosa: A Mad Max Saga",
      overview:
        "As the world fell, young Furiosa is snatched from the Green Place of Many Mothers and falls into the hands of a great Biker Horde led by the Warlord Dementus. Sweeping through the Wasteland they come across the Citadel presided over by The Immortan Joe. While the two Tyrants war for dominance, Furiosa must survive many trials as she puts together the means to find her way home.",
      popularity: 1464.685,
      poster_path: "/iADOJ8Zymht2JPMoy3R7xceZprc.jpg",
      release_date: "2024-05-22",
      title: "Furiosa: A Mad Max Saga",
      video: false,
      vote_average: 7.649,
      vote_count: 2318,
    },
    {
      adult: false,
      backdrop_path: "/fqv8v6AycXKsivp1T5yKtLbGXce.jpg",
      genre_ids: [878, 12, 28],
      id: 653346,
      original_language: "en",
      original_title: "Kingdom of the Planet of the Apes",
      overview:
        "Several generations following Caesar's reign, apes – now the dominant species – live harmoniously while humans have been reduced to living in the shadows. As a new tyrannical ape leader builds his empire, one young ape undertakes a harrowing journey that will cause him to question all he's known about the past and to make choices that will define a future for apes and humans alike.",
      popularity: 1649.421,
      poster_path: "/gKkl37BQuKTanygYQG1pyYgLVgf.jpg",
      release_date: "2024-05-08",
      title: "Kingdom of the Planet of the Apes",
      video: false,
      vote_average: 7.163,
      vote_count: 2095,
    },
    {
      adult: false,
      backdrop_path: "/dn3gbDpXPSwC6saMJOHkCiFA9jn.jpg",
      genre_ids: [14, 12, 10751, 35],
      id: 974262,
      original_language: "en",
      original_title: "Descendants: The Rise of Red",
      overview:
        "After the Queen of Hearts incites a coup on Auradon, her rebellious daughter Red and Cinderella's perfectionist daughter Chloe join forces and travel back in time to try to undo the traumatic event that set Red's mother down her villainous path.",
      popularity: 1401.886,
      poster_path: "/8fYluTtB3b3HKO7KQa5tzrvGaps.jpg",
      release_date: "2024-07-11",
      title: "Descendants: The Rise of Red",
      video: false,
      vote_average: 7.14,
      vote_count: 189,
    },
    {
      adult: false,
      backdrop_path: "/oSJV6nAfHzyE9v6oEAXmDjbko00.jpg",
      genre_ids: [14, 12],
      id: 943344,
      original_language: "zh",
      original_title: "地底怪物",
      overview:
        "Near a remote town, the repeated dumping of toxic waste causes an underground cave dweller to mutate into a hideous monster. A construction team that is digging a tunnel accidentally disturb the creature's habitat causing it to attack.",
      popularity: 888.404,
      poster_path: "/lWVwWRLqpS1OaNg7KT0ZecSW0PK.jpg",
      release_date: "2023-04-27",
      title: "Underground Monster",
      video: false,
      vote_average: 3.7,
      vote_count: 6,
    },
    {
      adult: false,
      backdrop_path: "/iIvjwrDPQHCU4NjbbKpNs88uk6G.jpg",
      genre_ids: [28, 35],
      id: 1048241,
      original_language: "en",
      original_title: "My Spy The Eternal City",
      overview:
        "JJ, a veteran CIA agent, reunites with his protégé Sophie, in order to prevent a catastrophic nuclear plot targeting the Vatican.",
      popularity: 1779.721,
      poster_path: "/Bf3vCfM94bSJ1saZlyi0UW0e0U.jpg",
      release_date: "2024-07-18",
      title: "My Spy The Eternal City",
      video: false,
      vote_average: 6.801,
      vote_count: 136,
    },
    {
      adult: false,
      backdrop_path: "/rrwt0u1rW685u9bJ9ougg5HJEHC.jpg",
      genre_ids: [28, 35, 80],
      id: 280180,
      original_language: "en",
      original_title: "Beverly Hills Cop: Axel F",
      overview:
        "Forty years after his unforgettable first case in Beverly Hills, Detroit cop Axel Foley returns to do what he does best: solve crimes and cause chaos.",
      popularity: 908.004,
      poster_path: "/zszRKfzjM5jltiq8rk6rasKVpUv.jpg",
      release_date: "2024-06-20",
      title: "Beverly Hills Cop: Axel F",
      video: false,
      vote_average: 6.897,
      vote_count: 706,
    },
    {
      adult: false,
      backdrop_path: "/qwhnq8pkFEAFXRwmscISOKK90Mu.jpg",
      genre_ids: [28, 53],
      id: 560016,
      original_language: "en",
      original_title: "Monkey Man",
      overview:
        "Kid is an anonymous young man who ekes out a meager living in an underground fight club where, night after night, wearing a gorilla mask, he is beaten bloody by more popular fighters for cash. After years of suppressed rage, Kid discovers a way to infiltrate the enclave of the city’s sinister elite. As his childhood trauma boils over, his mysteriously scarred hands unleash an explosive campaign of retribution to settle the score with the men who took everything from him.",
      popularity: 784.527,
      poster_path: "/4lhR4L2vzzjl68P1zJyCH755Oz4.jpg",
      release_date: "2024-04-03",
      title: "Monkey Man",
      video: false,
      vote_average: 7.053,
      vote_count: 645,
    },
    {
      adult: false,
      backdrop_path: "/wPNI1fd18z5TKBOK9Mv9Rfjb0j0.jpg",
      genre_ids: [53, 18, 28, 80],
      id: 729165,
      original_language: "en",
      original_title: "Out of Exile",
      overview:
        "Recently paroled thief Gabriel Russell tries to balance his life and mend a troubled family as an FBI agent hunts him down, along with his crew after a botched armored car robbery.",
      popularity: 1252.104,
      poster_path: "/jgF5XaXnJmOgMxulhy2k1f9LNNc.jpg",
      release_date: "2023-01-20",
      title: "Out of Exile",
      video: false,
      vote_average: 6.339,
      vote_count: 28,
    },
    {
      adult: false,
      backdrop_path: "/dbtGinhWWKgQLQ0hjZHMFWxBJcJ.jpg",
      genre_ids: [28, 878, 27, 53],
      id: 1159518,
      original_language: "en",
      original_title: "Black Noise",
      overview:
        "Members of an elite security team deployed to rescue a VIP on an exclusive island.The rescue mission becomes a desperate attempt to survive, escape the island and elude the sinister presence that seeks to harm them.",
      popularity: 727.967,
      poster_path: "/snKpXexv5dtWqEKEmXrJtp8QGQC.jpg",
      release_date: "2023-11-03",
      title: "Black Noise",
      video: false,
      vote_average: 5.278,
      vote_count: 18,
    },
    {
      adult: false,
      backdrop_path: "/59AJ2w9tKRSbBpnxKfB5UyIg6Jf.jpg",
      genre_ids: [27, 53],
      id: 1010600,
      original_language: "en",
      original_title: "The Strangers: Chapter 1",
      overview:
        "After their car breaks down in an eerie small town, a young couple are forced to spend the night in a remote cabin. Panic ensues as they are terrorized by three masked strangers who strike with no mercy and seemingly no motives.",
      popularity: 1098.172,
      poster_path: "/cdFZoQDxLRRWXLB3kxCnc674dBF.jpg",
      release_date: "2024-05-15",
      title: "The Strangers: Chapter 1",
      video: false,
      vote_average: 5.876,
      vote_count: 214,
    },
    {
      adult: false,
      backdrop_path: "/uNTciMXpCQDg7gvgMsPCdnxo6Re.jpg",
      genre_ids: [28, 53],
      id: 1114738,
      original_language: "en",
      original_title: "Boneyard",
      overview:
        'After Police Chief Carter discovers the remains of eleven women, FBI Special Agent Petrovick is recruited to profile the serial killer responsible for the infamous "boneyard" killings. As the police force, narcotics agency, and FBI lock horns, a tangled web of intrigue turns everyone into a suspect.',
      popularity: 651.204,
      poster_path: "/xkNK36hQv8SWiwiQoE7naRfP0zL.jpg",
      release_date: "2024-07-05",
      title: "Boneyard",
      video: false,
      vote_average: 5.728,
      vote_count: 46,
    },
    {
      adult: false,
      backdrop_path: "/adAJDB2Au3x5ve2YyWaEYy4EUw.jpg",
      genre_ids: [18, 10749, 35],
      id: 1191610,
      original_language: "es",
      original_title: "Goyo",
      overview:
        "A young autistic museum guide lives by a strict routine — until he falls in love with his coworker and must confront a whirlwind of new, intense emotions.",
      popularity: 634.582,
      poster_path: "/fCjC1RRbEJUpDjM55RNUMXQen0b.jpg",
      release_date: "2024-06-27",
      title: "Goyo",
      video: false,
      vote_average: 6.878,
      vote_count: 37,
    },
    {
      adult: false,
      backdrop_path: "/aATi2PtaOQCVAquCym6OU0Z4FjY.jpg",
      genre_ids: [28],
      id: 704673,
      original_language: "en",
      original_title: "Trigger Warning",
      overview:
        "A Special Forces commando uncovers a dangerous conspiracy when she returns to her hometown looking for answers into her beloved father's death.",
      popularity: 587.083,
      poster_path: "/lJN24nn28s5afC1UnLPYRgYOp1K.jpg",
      release_date: "2024-06-20",
      title: "Trigger Warning",
      video: false,
      vote_average: 5.822,
      vote_count: 353,
    },
    {
      adult: false,
      backdrop_path: "/xk2y81O2FljJwuyFP1HoJnCO8ed.jpg",
      genre_ids: [878, 28, 12],
      id: 823464,
      original_language: "en",
      original_title: "Godzilla x Kong: The New Empire",
      overview:
        "Following their explosive showdown, Godzilla and Kong must reunite against a colossal undiscovered threat hidden within our world, challenging their very existence – and our own.",
      popularity: 846.453,
      poster_path: "/z1p34vh7dEOnLDmyCrlUVLuoDzd.jpg",
      release_date: "2024-03-27",
      title: "Godzilla x Kong: The New Empire",
      video: false,
      vote_average: 7.189,
      vote_count: 3272,
    },
  ],
  total_pages: 49571,
  total_results: 991403,
};

export const tvData = {
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: "/w7oNyGaZ8Tz9LnAr0nf6dvKC968.jpg",
      genre_ids: [10764],
      id: 6390,
      origin_country: ["GB"],
      original_language: "en",
      original_name: "Escape to the Country",
      overview:
        "The property show that helps prospective buyers find their dream home in the country.",
      popularity: 3911.919,
      poster_path: "/ykSfW3rU7Th0VvrgB85nHvQZCAN.jpg",
      first_air_date: "2002-10-14",
      name: "Escape to the Country",
      vote_average: 4.864,
      vote_count: 22,
    },
    {
      adult: false,
      backdrop_path: "/7MscZ0FGf4bNP0pSIhQn3hz8GXl.jpg",
      genre_ids: [99],
      id: 3562,
      origin_country: ["US"],
      original_language: "en",
      original_name: "NOVA",
      overview:
        "PBS' premier science series helps viewers of all ages explore the science behind the headlines. Along the way, NOVA demystifies science and technology, and highlights the people involved in scientific pursuits.",
      popularity: 2035.613,
      poster_path: "/giUBXYnDAaJgNqA6iE3BMVE2EHp.jpg",
      first_air_date: "1974-03-03",
      name: "NOVA",
      vote_average: 6.836,
      vote_count: 110,
    },
    {
      adult: false,
      backdrop_path: "/mZCq3ldk7hUIyDvfZIOvTrxPWYS.jpg",
      genre_ids: [10764],
      id: 209374,
      origin_country: ["US"],
      original_language: "es",
      original_name: "Top Chef VIP",
      overview: "",
      popularity: 2002.834,
      poster_path: "/6Gy1ReRZ9sK9g8TPXZGz7CcQvrV.jpg",
      first_air_date: "2022-08-09",
      name: "Top Chef VIP",
      vote_average: 5.6,
      vote_count: 10,
    },
    {
      adult: false,
      backdrop_path: "/3u5b6Zy3EKQX0ALvg1uBC7wd1Jw.jpg",
      genre_ids: [35, 10767],
      id: 4419,
      origin_country: ["US"],
      original_language: "en",
      original_name: "Real Time with Bill Maher",
      overview:
        "Each week Bill Maher surrounds himself with a panel of guests which include politicians, actors, comedians, musicians and the like to discuss what's going on in the world.",
      popularity: 4005.045,
      poster_path: "/pbpoLLp4kvnYVfnEGiEhagpJuVZ.jpg",
      first_air_date: "2003-02-21",
      name: "Real Time with Bill Maher",
      vote_average: 6.028,
      vote_count: 197,
    },
    {
      adult: false,
      backdrop_path: "/w9zV6lOILeqaOilJzI1Xa9NRhXY.jpg",
      genre_ids: [10759, 18, 10751, 35],
      id: 5368,
      origin_country: ["US"],
      original_language: "en",
      original_name: "Lassie",
      overview:
        "Lassie is the pet of Jeff Miller, an 11-year-old farm boy. The two become best friends and enjoy family adventures in the American countryside, teaching each other about love, nature and commitment.",
      popularity: 2634.645,
      poster_path: "/vqbVr4fYRZb28ywczaidn29JJTA.jpg",
      first_air_date: "1954-09-12",
      name: "Lassie",
      vote_average: 6.056,
      vote_count: 62,
    },
    {
      adult: false,
      backdrop_path: "/tuMZKK47l6l42lql9fC6PV6S06M.jpg",
      genre_ids: [80, 18, 9648],
      id: 4057,
      origin_country: ["US"],
      original_language: "en",
      original_name: "Criminal Minds",
      overview:
        "An elite team of FBI profilers analyze the country's most twisted criminal minds, anticipating their next moves before they strike again. The Behavioral Analysis Unit's most experienced agent is David Rossi, a founding member of the BAU who returns to help the team solve new cases.",
      popularity: 1909.294,
      poster_path: "/wLMQebhTApmn4F6Fzg6FovdwVvL.jpg",
      first_air_date: "2005-09-22",
      name: "Criminal Minds",
      vote_average: 8.313,
      vote_count: 3646,
    },
    {
      adult: false,
      backdrop_path: "/AqhMVAeGQNtBQbD2HJf2m2KrrUX.jpg",
      genre_ids: [10766, 18],
      id: 4275,
      origin_country: ["AU"],
      original_language: "en",
      original_name: "Prisoner: Cell Block H",
      overview:
        "Prisoner is an Australian soap opera that is set in the Wentworth Detention Centre, a fictional women's prison.",
      popularity: 3535.026,
      poster_path: "/9OSK44nb6ZZkMxkX6SLeQszVFke.jpg",
      first_air_date: "1979-02-27",
      name: "Prisoner: Cell Block H",
      vote_average: 7.5,
      vote_count: 27,
    },
    {
      adult: false,
      backdrop_path: "/6MWmIGqZpyPO5fjBFII5gmBYsFX.jpg",
      genre_ids: [99],
      id: 2394,
      origin_country: ["US"],
      original_language: "en",
      original_name: "This Old House",
      overview:
        "TV's original home-improvement show, following one whole-house renovation over several episodes.",
      popularity: 1697.029,
      poster_path: "/ecAOX4esywAXLF5I4X2gaTmhmAG.jpg",
      first_air_date: "1979-01-01",
      name: "This Old House",
      vote_average: 5.15,
      vote_count: 30,
    },
    {
      adult: false,
      backdrop_path: "/pPUtOmorFMI2q5OF77r9GDcZTkX.jpg",
      genre_ids: [10764],
      id: 30957,
      origin_country: ["GB", "US"],
      original_language: "en",
      original_name: "The Amazing Race",
      overview:
        "This reality competition sees teams embark on a trek around the world to amazing destinations where they must compete in a series of challenges, some mental and some physical. Only when the tasks are completed will they learn of their next location. Teams who are the farthest behind will gradually be eliminated as the contest progresses, with the first team to arrive at the final destination winning the race and the $1 million prize.",
      popularity: 3138.687,
      poster_path: "/x1jq0atcQg6UkaZpco0kFL6QHuM.jpg",
      first_air_date: "2001-09-05",
      name: "The Amazing Race",
      vote_average: 6.863,
      vote_count: 135,
    },
    {
      adult: false,
      backdrop_path: "/etj8E2o0Bud0HkONVQPjyCkIvpv.jpg",
      genre_ids: [10765, 18, 10759],
      id: 94997,
      origin_country: ["US"],
      original_language: "en",
      original_name: "House of the Dragon",
      overview:
        "The Targaryen dynasty is at the absolute apex of its power, with more than 15 dragons under their yoke. Most empires crumble from such heights. In the case of the Targaryens, their slow fall begins when King Viserys breaks with a century of tradition by naming his daughter Rhaenyra heir to the Iron Throne. But when Viserys later fathers a son, the court is shocked when Rhaenyra retains her status as his heir, and seeds of division sow friction across the realm.",
      popularity: 2458.681,
      poster_path: "/7QMsOTMUswlwxJP0rTTZfmz2tX2.jpg",
      first_air_date: "2022-08-21",
      name: "House of the Dragon",
      vote_average: 8.411,
      vote_count: 4517,
    },
    {
      adult: false,
      backdrop_path: "/zZqpAXxVSBtxV9qPBcscfXBcL2w.jpg",
      genre_ids: [10765, 18, 10759],
      id: 1399,
      origin_country: ["US"],
      original_language: "en",
      original_name: "Game of Thrones",
      overview:
        "Seven noble families fight for control of the mythical land of Westeros. Friction between the houses leads to full-scale war. All while a very ancient evil awakens in the farthest north. Amidst the war, a neglected military order of misfits, the Night's Watch, is all that stands between the realms of men and icy horrors beyond.",
      popularity: 2929.214,
      poster_path: "/1XS1oqL89opfnbLl8WnZY1O1uJx.jpg",
      first_air_date: "2011-04-17",
      name: "Game of Thrones",
      vote_average: 8.453,
      vote_count: 23513,
    },
    {
      adult: false,
      backdrop_path: "/tMRdEsMg9MyXAkcufK9YJEeIaNW.jpg",
      genre_ids: [35],
      id: 1400,
      origin_country: ["US"],
      original_language: "en",
      original_name: "Seinfeld",
      overview:
        "A stand-up comedian and his three offbeat friends weather the pitfalls and payoffs of life in New York City in the '90s. It's a show about nothing.",
      popularity: 2878.849,
      poster_path: "/aCw8ONfyz3AhngVQa1E2Ss4KSUQ.jpg",
      first_air_date: "1989-07-05",
      name: "Seinfeld",
      vote_average: 8.279,
      vote_count: 1908,
    },
    {
      adult: false,
      backdrop_path: "/5UNcEz7Lc3OGilpPn1Tb9cd1xsc.jpg",
      genre_ids: [35, 10767],
      id: 1220,
      origin_country: ["GB"],
      original_language: "en",
      original_name: "The Graham Norton Show",
      overview:
        "Each week celebrity guests join Irish comedian Graham Norton to discuss what's being going on around the world that week. The guests poke fun and share their opinions on the main news stories. Graham is often joined by a band or artist to play the show out.",
      popularity: 3226.819,
      poster_path: "/vrbqaBXB8AALynQzpWz6JdCPEJS.jpg",
      first_air_date: "2007-02-22",
      name: "The Graham Norton Show",
      vote_average: 7.143,
      vote_count: 245,
    },
    {
      adult: false,
      backdrop_path: "/4TK1IREtfd7Ki8JWfwR1WahO5IP.jpg",
      genre_ids: [16, 35],
      id: 4606,
      origin_country: ["US"],
      original_language: "en",
      original_name: "Garfield and Friends",
      overview:
        "The animated stories of Garfield the cat, Odie the dog, their owner Jon and the trouble they get into. And also Orson the Pig and his adventures on a farm with his fellow farm animals.",
      popularity: 2665.713,
      poster_path: "/3HyTfZ9sSCoZPYrYHMffhRVm3Af.jpg",
      first_air_date: "1988-09-17",
      name: "Garfield and Friends",
      vote_average: 7.2,
      vote_count: 342,
    },
    {
      adult: false,
      backdrop_path: "/4bzSEBjVb3QwPaJ39Rp2gmH9Bug.jpg",
      genre_ids: [35],
      id: 3690,
      origin_country: ["US"],
      original_language: "en",
      original_name: "House of Payne",
      overview:
        "The show revolved around a multi-generational family living under one roof in Atlanta led by patriarch Curtis Payne and his wife Ella.",
      popularity: 2780.159,
      poster_path: "/2NdUdJnZnwI6skvm6OXWrK2D42U.jpg",
      first_air_date: "2007-06-06",
      name: "House of Payne",
      vote_average: 7.6,
      vote_count: 48,
    },
    {
      adult: false,
      backdrop_path: "/m2D5bhoAB0ewe42m8rfIl0a1ahM.jpg",
      genre_ids: [9648, 80, 10759],
      id: 211089,
      origin_country: ["CN"],
      original_language: "zh",
      original_name: "唐朝诡事录",
      overview:
        "When the dark evil immortal descends from the heaven, and the mysterious underground ghost palace was revealed, a strange herb named the Black Tea suddenly took Chang'an City by storm. However, no one knows whether it is a healthy medicine or one that could harm people. Cases of missing brides in Chang'an City began occurring one after another, which seems to be inextricably linked to the black tea...  Ling Feng, general of the Jin Wu guards was tasked to investigate these cases. On his journey, he meets his strongest opponent in Su Wu Ming, the disciple of Di Ren Jie. The two of them work together to solve these mysterious cases.",
      popularity: 2931.807,
      poster_path: "/y8a0sXfO1tn5KGH6mRVn7FnPdkW.jpg",
      first_air_date: "2022-09-27",
      name: "Strange Tales Of Tang Dynasty",
      vote_average: 8.1,
      vote_count: 16,
    },
    {
      adult: false,
      backdrop_path: "/coHpOy9OJyFiHWeH36cSHMpLUHC.jpg",
      genre_ids: [35],
      id: 2691,
      origin_country: ["US"],
      original_language: "en",
      original_name: "Two and a Half Men",
      overview:
        "A hedonistic jingle writer's free-wheeling life comes to an abrupt halt when his brother and 10-year-old nephew move into his beach-front house.",
      popularity: 3082.064,
      poster_path: "/xgfjxyV3g1S68opzuvG6G87muDp.jpg",
      first_air_date: "2003-09-22",
      name: "Two and a Half Men",
      vote_average: 7.46,
      vote_count: 3115,
    },
    {
      adult: false,
      backdrop_path: "/dAepkmD4vdfhS82r2OIqF1nwGR5.jpg",
      genre_ids: [10759, 18, 80, 9648],
      id: 17610,
      origin_country: ["US"],
      original_language: "en",
      original_name: "NCIS: Los Angeles",
      overview:
        "The exploits of the Los Angeles–based Office of Special Projects (OSP), an elite division of the Naval Criminal Investigative Service that specializes in undercover assignments.",
      popularity: 3013.029,
      poster_path: "/TIIgcznwNfNr3KOZvxn26eKV99.jpg",
      first_air_date: "2009-09-22",
      name: "NCIS: Los Angeles",
      vote_average: 7.543,
      vote_count: 1123,
    },
    {
      adult: false,
      backdrop_path: "/chvL3XiWE8Oa9NVEeIJpY4VvrW.jpg",
      genre_ids: [10764],
      id: 62481,
      origin_country: ["US"],
      original_language: "en",
      original_name: "Beat Bobby Flay",
      overview:
        "Two talented chefs go head-to-head for the chance to Beat Bobby Flay. To get to Bobby the chefs must first face off against each other, creating a spectacular dish with a secret ingredient of Bobby's choice. Judges Alex Guarnaschelli and Jeff Mauro know Bobby's strengths and his weaknesses. Their goal: Pick the chef who has the skills to take down Bobby Flay in his own arena. The winning chef gets to challenge Bobby with his or her surprise signature dish. If Bobby goes down, the winner can tell the world, \"I beat Bobby Flay!\"",
      popularity: 2403.131,
      poster_path: "/caB0IxcYHL5roqDf4KIjICRY5LK.jpg",
      first_air_date: "2013-08-24",
      name: "Beat Bobby Flay",
      vote_average: 6.7,
      vote_count: 21,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [35, 10767],
      id: 3430,
      origin_country: ["GB"],
      original_language: "en",
      original_name: "The Paul O'Grady Show",
      overview:
        "The Paul O'Grady Show is a British comedy chat show hosted by Birkenhead-born comedian Paul O'Grady. The format was originally devised by Granada Television and was broadcast on ITV before moving to Channel 4, where the show was produced by Olga TV. The programme is a teatime chat show consisting of a mixture of celebrity guests, comic stunts, musical performances, and occasionally viewer competitions.",
      popularity: 2905.981,
      poster_path: "/fGoZnpbWxcrjKn8z7Auq47SvxST.jpg",
      first_air_date: "2004-10-11",
      name: "The Paul O'Grady Show",
      vote_average: 4.4,
      vote_count: 9,
    },
  ],
  total_pages: 8931,
  total_results: 178618,
};
